version: '3.7'
services:
  devclass-api:
    container_name: devclass-api
    depends_on:
      - redis
    expose:
      - "5000"    
  redis:
    image: "redis:4.0-alpine"
    container_name: app-redis
    expose:
      - "6379"
