version: '3.7'
services:
  db:    
    env_file:
      - ../../.env.production
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata 
    volumes:
      - /var/lib/postgresql/api/data/pgdata:/var/lib/postgresql/data/pgdata
